/**
 * 商业航天发射追踪 - 数据源定义
 */

import type { DataSource } from './types';

export const DATA_SOURCES: DataSource[] = [
  {
    id: 'launch_library2',
    name: 'Launch Library 2',
    nameZh: 'Launch Library 2（The Space Devs）',
    description: 'The Space Devs Launch Library 2 - comprehensive global launch database with detailed mission data',
    descriptionZh: 'The Space Devs 维护的全球最全面发射数据库，包含详细任务、火箭、发射场信息',
    url: 'https://thespacedevs.com/llapi',
    apiUrl: 'https://ll.thespacedevs.com/2.3.0/launches/upcoming/?format=json&limit=25&mode=detailed',
    updateInterval: 300,
    requiresApiKey: false,
    free: true,
    coverage: 'global',
    color: '#4488ff',
    icon: '🛸',
  },
  {
    id: 'spacex_api',
    name: 'SpaceX API',
    nameZh: 'SpaceX 官方 API',
    description: 'Official SpaceX API - Falcon 9, Falcon Heavy, Starship launches with detailed telemetry',
    descriptionZh: 'SpaceX 官方 API，猎鹰9号、重型猎鹰、星舰发射数据及详细遥测信息',
    url: 'https://github.com/r-spacex/SpaceX-API',
    apiUrl: 'https://api.spacexdata.com/v5/launches/upcoming',
    updateInterval: 600,
    requiresApiKey: false,
    free: true,
    coverage: 'partial',
    color: '#ffffff',
    icon: '🚀',
  },
  {
    id: 'rocketlaunch_live',
    name: 'RocketLaunch.Live',
    nameZh: 'RocketLaunch.Live',
    description: 'RocketLaunch.Live - near real-time launch schedule with countdown and status updates',
    descriptionZh: 'RocketLaunch.Live 近实时发射时间表，含倒计时和状态更新',
    url: 'https://rocketlaunch.live',
    apiUrl: 'https://fdo.rocketlaunch.live/json/launches/next/5',
    updateInterval: 120,
    requiresApiKey: false,
    free: true,
    coverage: 'global',
    color: '#ff8844',
    icon: '📡',
  },
  {
    id: 'thespacedevs',
    name: 'The Space Devs (LL2 Snapi)',
    nameZh: 'The Space Devs 精简版',
    description: 'The Space Devs snapi endpoint - lightweight launch data for quick queries',
    descriptionZh: 'The Space Devs 精简接口，快速获取近期发射数据',
    url: 'https://thespacedevs.com',
    apiUrl: 'https://ll.thespacedevs.com/2.3.0/launches/upcoming/?format=json&limit=10&mode=list',
    updateInterval: 180,
    requiresApiKey: false,
    free: true,
    coverage: 'global',
    color: '#44ffaa',
    icon: '🌐',
  },
  {
    id: 'nextspaceflight',
    name: 'Next Spaceflight',
    nameZh: 'Next Spaceflight',
    description: 'Next Spaceflight - curated launch schedule with mission descriptions',
    descriptionZh: 'Next Spaceflight 精选发射时间表，含任务描述',
    url: 'https://nextspaceflight.com',
    apiUrl: 'https://ll.thespacedevs.com/2.3.0/launches/previous/?format=json&limit=20&mode=detailed',
    updateInterval: 3600,
    requiresApiKey: false,
    free: true,
    coverage: 'global',
    color: '#aa88ff',
    icon: '🔭',
  },
];

export const DATA_SOURCE_MAP = new Map(DATA_SOURCES.map(s => [s.id, s]));
