/**
 * 性能基线脚本
 *
 * 构建项目并生成性能基线报告（体积、路由数量等）。
 * 与 perf:lighthouse 配合使用，记录"改动前/改动后"的对比基准。
 *
 * 用法:
 *   npm run perf:baseline
 */
import { execSync } from 'child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'fs';
import { join, relative } from 'path';

const ROOT = join(__dirname, '..');
const NEXT_DIR = join(ROOT, '.next');
const REPORTS_DIR = join(ROOT, 'reports', 'baseline');

function getDirSize(dir: string): number {
  if (!existsSync(dir)) return 0;
  let total = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isFile()) total += statSync(fullPath).size;
    else if (entry.isDirectory()) total += getDirSize(fullPath);
  }
  return total;
}

function collectFileSizes(dir: string, baseDir = dir): Record<string, number> {
  const result: Record<string, number> = {};
  if (!existsSync(dir)) return result;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isFile()) {
      result[relative(baseDir, fullPath)] = statSync(fullPath).size;
    } else if (entry.isDirectory()) {
      Object.assign(result, collectFileSizes(fullPath, baseDir));
    }
  }
  return result;
}

function main() {
  if (!existsSync(NEXT_DIR)) {
    console.log('No .next directory found. Run "npm run build" first.');
    process.exit(1);
  }

  if (!existsSync(REPORTS_DIR)) {
    mkdirSync(REPORTS_DIR, { recursive: true });
  }

  const staticDir = join(NEXT_DIR, 'static');
  const serverDir = join(NEXT_DIR, 'server');

  const staticJsSize = getDirSize(join(staticDir));
  const serverSize = getDirSize(serverDir);

  const buildManifestPath = join(NEXT_DIR, 'build-manifest.json');
  const routesManifestPath = join(NEXT_DIR, 'routes-manifest.json');

  const buildManifest = existsSync(buildManifestPath)
    ? JSON.parse(readFileSync(buildManifestPath, 'utf-8'))
    : {};
  const routesManifest = existsSync(routesManifestPath)
    ? JSON.parse(readFileSync(routesManifestPath, 'utf-8'))
    : {};

  const routeCount = routesManifest.staticRoutes?.length ?? 0;

  const pageEntries = buildManifest.pages ?? {};
  const pageCount = Object.keys(pageEntries).length;

  const staticFiles = collectFileSizes(staticDir);

  const baseline = {
    timestamp: new Date().toISOString(),
    version: process.env.npm_package_version || 'unknown',
    build: {
      totalStaticSize: staticJsSize,
      totalServerSize: serverSize,
      pageCount,
      routeCount,
    },
    staticFiles,
    notes: 'Baseline generated by perf-baseline script. Compare against future runs.',
  };

  const baselinePath = join(REPORTS_DIR, 'baseline.json');
  writeFileSync(baselinePath, JSON.stringify(baseline, null, 2));

  console.log('\nPerformance Baseline Report');
  console.log('='.repeat(40));
  console.log(`  Timestamp:     ${baseline.timestamp}`);
  console.log(`  Version:       ${baseline.version}`);
  console.log(`  Static JS:     ${(staticJsSize / 1024 / 1024).toFixed(2)} MB`);
  console.log(`  Server output: ${(serverSize / 1024 / 1024).toFixed(2)} MB`);
  console.log(`  Pages:         ${pageCount}`);
  console.log(`  Routes:        ${routeCount}`);
  console.log(`\n  Baseline saved to: ${baselinePath}`);
}

main();
