/**
 * 全球货运与贸易路线追踪 - 数据源定义
 */

import type { TrafficDataSource } from './types';

export const TRAFFIC_DATA_SOURCES: TrafficDataSource[] = [
  // ── 船舶 AIS ──────────────────────────────────────────────
  {
    id: 'aisstream',
    name: 'AISstream.io',
    nameZh: 'AISstream 实时AIS',
    category: 'vessel',
    description: 'Free WebSocket AIS stream - real-time global vessel positions (API key required, free tier available)',
    descriptionZh: '免费WebSocket AIS数据流，实时全球船舶位置（需免费API Key）',
    url: 'https://aisstream.io',
    apiUrl: 'wss://stream.aisstream.io/v0/stream',
    updateInterval: 5,
    requiresApiKey: true,
    apiKeyUrl: 'https://aisstream.io/authenticate',
    free: true,
    coverage: 'global',
    color: '#00aaff',
    icon: '🚢',
    dataFormat: 'websocket',
  },
  {
    id: 'marinetraffic_free',
    name: 'MarineTraffic (Expected Arrivals)',
    nameZh: 'MarineTraffic 预期到港',
    category: 'vessel',
    description: 'MarineTraffic free expected arrivals API - vessel traffic at major ports',
    descriptionZh: 'MarineTraffic免费预期到港API，主要港口船舶流量',
    url: 'https://www.marinetraffic.com',
    apiUrl: 'https://services.marinetraffic.com/api/expectedarrivals/v:1',
    updateInterval: 300,
    requiresApiKey: true,
    apiKeyUrl: 'https://www.marinetraffic.com/en/online-services/plans',
    free: false,
    coverage: 'global',
    color: '#0077cc',
    icon: '⚓',
    dataFormat: 'json',
  },
  {
    id: 'vesselfinder_free',
    name: 'VesselFinder',
    nameZh: 'VesselFinder 船舶追踪',
    category: 'vessel',
    description: 'VesselFinder public vessel positions - major shipping lanes',
    descriptionZh: 'VesselFinder公开船舶位置数据，主要航运航道',
    url: 'https://www.vesselfinder.com',
    apiUrl: 'https://api.vesselfinder.com/vessels',
    updateInterval: 60,
    requiresApiKey: true,
    apiKeyUrl: 'https://www.vesselfinder.com/api',
    free: false,
    coverage: 'global',
    color: '#0055aa',
    icon: '🛳️',
    dataFormat: 'json',
  },

  // ── 航班 ──────────────────────────────────────────────────
  {
    id: 'opensky',
    name: 'OpenSky Network',
    nameZh: 'OpenSky 开放天空网络',
    category: 'flight',
    description: 'OpenSky Network - free real-time flight tracking, no API key needed for anonymous access',
    descriptionZh: 'OpenSky开放天空网络，免费实时航班追踪，匿名访问无需API Key',
    url: 'https://opensky-network.org',
    apiUrl: 'https://opensky-network.org/api/states/all',
    updateInterval: 10,
    requiresApiKey: false,
    free: true,
    coverage: 'global',
    color: '#ff8800',
    icon: '✈️',
    dataFormat: 'json',
  },
  {
    id: 'adsbexchange',
    name: 'ADS-B Exchange',
    nameZh: 'ADS-B Exchange 航班数据',
    category: 'flight',
    description: 'ADS-B Exchange - unfiltered real-time flight data, free API available',
    descriptionZh: 'ADS-B Exchange未过滤实时航班数据，提供免费API',
    url: 'https://www.adsbexchange.com',
    apiUrl: 'https://opendata.adsbexchange.com/flight-data/readsb-hist',
    updateInterval: 15,
    requiresApiKey: false,
    free: true,
    coverage: 'global',
    color: '#ffaa00',
    icon: '🛩️',
    dataFormat: 'json',
  },
  {
    id: 'flightradar24_free',
    name: 'Flightradar24 (Public)',
    nameZh: 'Flightradar24 公开数据',
    category: 'flight',
    description: 'Flightradar24 public flight data endpoint - limited but no key required',
    descriptionZh: 'Flightradar24公开航班数据接口，有限制但无需API Key',
    url: 'https://www.flightradar24.com',
    apiUrl: 'https://data-cloud.flightradar24.com/zones/fcgi/feed.js',
    updateInterval: 10,
    requiresApiKey: false,
    free: true,
    coverage: 'global',
    color: '#ffcc00',
    icon: '🛫',
    dataFormat: 'json',
  },

  // ── 港口与机场 ────────────────────────────────────────────
  {
    id: 'worldports',
    name: 'World Port Index',
    nameZh: '世界港口索引',
    category: 'port',
    description: 'NGIA World Port Index - comprehensive global seaport database (static)',
    descriptionZh: '美国国家地理空间情报局世界港口索引，全球海港综合数据库（静态）',
    url: 'https://msi.nga.mil/Publications/WPI',
    apiUrl: 'https://msi.nga.mil/api/publications/world-port-index?output=json',
    updateInterval: 86400,
    requiresApiKey: false,
    free: true,
    coverage: 'global',
    color: '#00ccaa',
    icon: '⚓',
    dataFormat: 'json',
  },
  {
    id: 'ourairports',
    name: 'OurAirports',
    nameZh: 'OurAirports 机场数据库',
    category: 'airport',
    description: 'OurAirports.com - free global airport database with coordinates (static CSV)',
    descriptionZh: 'OurAirports.com免费全球机场数据库，含坐标（静态CSV）',
    url: 'https://ourairports.com',
    apiUrl: 'https://davidmegginson.github.io/ourairports-data/airports.csv',
    updateInterval: 86400,
    requiresApiKey: false,
    free: true,
    coverage: 'global',
    color: '#aaaaff',
    icon: '🛬',
    dataFormat: 'csv',
  },

  // ── 贸易航线 ──────────────────────────────────────────────
  {
    id: 'natural_earth_routes',
    name: 'Natural Earth Shipping Lanes',
    nameZh: 'Natural Earth 航运航道',
    category: 'trade_route',
    description: 'Natural Earth Data - major world shipping lanes (static GeoJSON)',
    descriptionZh: 'Natural Earth数据集，主要世界航运航道（静态GeoJSON）',
    url: 'https://www.naturalearthdata.com',
    apiUrl: 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_geography_marine_polys.geojson',
    updateInterval: 86400,
    requiresApiKey: false,
    free: true,
    coverage: 'global',
    color: '#4488ff',
    icon: '🗺️',
    dataFormat: 'geojson',
  },
  {
    id: 'ihs_sea_routes',
    name: 'Sea Routes (OpenStreetMap)',
    nameZh: 'OSM 海上航线',
    category: 'trade_route',
    description: 'OpenStreetMap-derived major sea routes and shipping corridors',
    descriptionZh: '基于OpenStreetMap的主要海上航线和航运走廊',
    url: 'https://www.openstreetmap.org',
    apiUrl: 'https://overpass-api.de/api/interpreter',
    updateInterval: 86400,
    requiresApiKey: false,
    free: true,
    coverage: 'global',
    color: '#2266dd',
    icon: '🌊',
    dataFormat: 'json',
  },
  {
    id: 'cargo_tracker_demo',
    name: 'Demo Cargo Routes',
    nameZh: '演示货运路线',
    category: 'trade_route',
    description: 'Built-in demonstration of major global trade corridors (no API needed)',
    descriptionZh: '内置主要全球贸易走廊演示数据，无需API',
    url: '',
    apiUrl: '',
    updateInterval: 0,
    requiresApiKey: false,
    free: true,
    coverage: 'global',
    color: '#88ddff',
    icon: '📦',
    dataFormat: 'static',
  },
];

export const DATA_SOURCE_MAP = new Map(TRAFFIC_DATA_SOURCES.map(s => [s.id, s]));

export const CATEGORY_LABELS: Record<string, { zh: string; en: string; icon: string; color: string }> = {
  vessel:      { zh: '船舶',     en: 'Vessels',      icon: '🚢', color: '#00aaff' },
  flight:      { zh: '航班',     en: 'Flights',      icon: '✈️', color: '#ff8800' },
  trade_route: { zh: '贸易航线', en: 'Trade Routes', icon: '🗺️', color: '#4488ff' },
  port:        { zh: '港口',     en: 'Ports',        icon: '⚓', color: '#00ccaa' },
  airport:     { zh: '机场',     en: 'Airports',     icon: '🛬', color: '#aaaaff' },
  multi:       { zh: '综合',     en: 'Multi',        icon: '🌐', color: '#ffffff' },
};
